#!/usr/bin/env bash

cp ~/.bashrc ./config/
cp ~/.Xresources ./config/
cp ~/.Xdefaults ./config/


#Copy scripts over
cp -rf ~/.scripts/* ./scripts/

#Copy over vim stuff
cp -rf ~/.vim/UltiSnips ./vim/*
cp ~/.vimrc ./vim/.vimrc

#Copy over config files
cp ~/.config/i3/* ./config/i3/
cp ~/.config/mutt/muttrc ./config/mutt/muttrc
cp ~/.config/polybar/* ./config/polybar/
cp -rf ~/.config/sxiv/* ./config/sxiv/
