#!/usr/bin/env bash
#Network Manager Mommand Line Interface DEvice WIFI
nmcli dev wifi | head -15

SSID=$(sudo iwlist wlp4s0 scan | grep SSID | sed 's/[^"]*"\([^"]*\)".*/\1/' | grep . | grep -v "x00"| sort -u | dmenu -l 15)

nmcli device wifi connect "$SSID"


